pipeline {
    agent { label 'nodejs' }

    // Set your OCP project
    environment { APP_NAMESPACE = 'rht-nlind-metrics' }

    stages{

        stage('Test'){
            steps {
                dir('greeting-cd-pipeline') {
                    sh "node test.js"
                }

            }
        }

        stage('Deploy'){
            steps {
                sh '''
                    oc start-build greeting-metrics \
                    --follow --wait -n ${APP_NAMESPACE}
                '''
            }
        }
    }
}
