pipeline{
    agent any
    stages{
        stage('Deploy'){
            steps{
                sh '''
                    oc project rht-nlind-deploy-strategies
                    oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}
